#pragma config(Sensor, dgtl1,  shaftEncoder1,  sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  change,         sensorTouch)
#pragma config(Sensor, dgtl4,  bumpSensor,     sensorTouch)
#pragma config(Sensor, dgtl5,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl6,  ultSensor,      sensorSONAR_mm)
#pragma config(Sensor, dgtl8,  limitSwitch2,   sensorTouch)
#pragma config(Sensor, dgtl9,  shaftEncoder2,  sensorQuadEncoder)
#pragma config(Motor,  port2,           motor1,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           motor2,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           servo,         tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//MOTOR VALUES:
//	-claw servo:
//			Open(during can finding): -70
//			Closed(grabbing can): 100
//  -Motors:
//		Bicep: 50, Negative up, positive down
//    Forearm: 30, negative up, positive down



task main()
{
	int times = 0;
	while (times < 3){ //number of times while loop runs, 1 time for each can
	SensorValue[shaftEncoder1] = 0; //set shaft encoder values to 0
	SensorValue[shaftEncoder2] = 0;
	int dist = SensorValue[ultSensor]; //ultrasonic value which is how far can is from
									   //the ultrasonic sensor

	//DOWNWARD MOTION OF BICEP
	bool down = true;
	int a = dist*24.72 - 3574.6; //equation generated from linear regression for shaftencoder2
	int b = dist*0.4074 - 229.03; //equation generated from linear regression for shaftencoder1
	motor[servo] = -70; //claw set to open
	motor[motor1] = 30; //move bicep towards tje can
	motor[motor2] = 0;
	//wait1Msec(10000);


		while(SensorValue[shaftEncoder2] > -a){ //move bicep until it gets to set position 
								//based on shaft encoder value from linear regression equation
			wait1Msec(10);
		}

		//STOP BICEP AND MOVE FOREARM DOWN
		motor[motor1] = 0; //stop moving bicep, start moving the forearm
		motor[motor2] = 30;
		while(SensorValue[shaftEncoder1] < -b){ //move forearm until it gets to set position 
							//based on shaft encoder value from linear regression equation
			wait1Msec(10);
		}

		//STOP FOREARM AND PICK UP CAN
		motor[motor2] = 0; //stop moving forearm
	  motor[servo] = 100; //close claw to hold can
	  down = false;


	  //MOVE BICEP UP
	  motor[motor1] = -30; //start moving bicep back towards the limit switch
		motor[motor2] = 0;

	while (true){ //if bump sensor is hit, move bicep back towards the top/limit switch
		int bump = SensorValue[bumpSensor];
	  int limit = SensorValue[limitSwitch];
	  int changeDirection = SensorValue[change];
		if (bump == 1){
		motor[motor1]= -30;
		motor[motor2]= 0;
		wait1Msec(5000);
		break;
	}


	//DROP CAN BEHIND ROBOT
	if (limit == 1 && down==false){ //if limit switch is hit, stop moving bicep
		//Bicep motion limit reached
		motor[motor1]=0;
		motor[motor2]=-30;
		//Move forearm back behind elbow/base
		while(SensorValue[limitSwitch2] == 0){ //forearm moves back until other 
														//limit switch is hit
			wait1Msec(1);
		}
		motor[motor2] = 0; //stop moving forearm

		//release can once forearm limit reached
		motor[servo] = -70; //open the claw
	  wait1Msec(1000); //pause for one second
		break;
	}
	if (changeDirection==1){ //code not used
		motor[motor1]=motor[motor1] * -1;
		motor[motor2]=motor[motor2] * -1;
		}
	}
	times = times+1;
	down = true;

}
}